name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo # Define o timezone no nível do job
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Verify Timezone
        run: |
          echo "Timezone configurado como: $TZ"
          date

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          publish-summary: true

      - name: Chrome - Upload Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: cypress/reports
          if-no-files-found: ignore

      - name: Chrome - Upload Snapshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Visual Regression
          path: cypress/snapshots
          if-no-files-found: ignore
